FROM python:3.9

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY data_import.py .
COPY .env .

COPY import_script.py /app/import_script.py

ENTRYPOINT ["python"]
